config/routes.rb
CookbookHeritage::Application.routes.draw do

  # Pages
  get "faq", to: "pages#faq", as: "faq"

  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "session_expiry_time", to: "sessions#testing"
  resources :sessions

  resources :cookbooks do
    member do
      get :select
      put :update_attachment
      get :edit_introduction
      put :update_introduction
      put :update_introduction_attachment
      get :edit_title
      put :update_title
      get :preview
      get :preview_cover
      get :preview_title_and_toc
      get :preview_index
      get :preview_introduction
      get :check_price
      get :count_page
    end
  end

  get "signup", to: "accounts#new", as: "signup"
  get "recover_password", to: "accounts#recover_password", as: "recover_password"
  post "new_password", to: "accounts#new_password", as: "new_password"
  resources :accounts do
    member do 
      get  :edit_password
      put  :update_password
      get  "upgrade/(:plan_id)", to: "accounts#upgrade", as: "upgrade"
      get  :edit_additional_information
      put  :update_additional_information
      post :process_payment
      get  :payment_processed
    end
  end

  resources :lib_images do
    member do
      get :select
    end
  end

  resources :templates do
    member do
      get :select
    end
  end

  resources :contributors do
    member do
      get :resend_invite
    end
  end

  resources :sections do
    collection do
      post :sort
    end
    resources :recipes do
      member do
        get :preview
        put :update_attachment
        post :update_attachment
      end
    end
    resources :extra_pages do
      member do
        get :preview
        put :update_attachment
      end
    end
    member do
      get :preview
      put :update_attachment
    end
  end
  
  resources :orders do
    member do 
      get :ask_price_quote
      get :edit_customer_details
      put :update_customer_details
      get :confirm
      post :create_price_quote
      get :approved
      get :declined
      get :notify_binding_problem
      get :reorder
      put :update_reorder
      get :guest
    end
  end

  # Cookbook previews workers management.
  get "previews/status"
  get "previews/download"

  namespace :admin do
    resources :users do
      member do
        get :login_as
        get  "update_expiry_date/:days", to: "users#update_expiry_date", as: "update_expiry_date"
      end
    end
    get "orders/new/:cookbook_id", to: "orders#new", as: "new_order"
    resources :orders, except: :new
    resources :image_library, except: :show
  end

  # Very basic API
  namespace :api do
    post "cookbook_cost_calculator/printing"
  end

  root to: "cookbooks#index"
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController

  # User needs to be authenticated.
  before_filter :authenticated?

  # User need to have a cookbook selected
  before_filter :cookbook_selected?, except: [:index, :select, :new]

  # User account must not be expired.
  before_filter :account_expired?, except: [:index, :select]

  # Selected cookbook design must be set.
  before_filter :design_set?, except: [:index, :select, :new, :edit_title, :update_title, :update]

  # User must not be a contributor
  before_filter :cookbook_owner?, except: [
    :index, :select, :new, :show_introduction,
    :preview, :preview_cover, :preview_title_and_toc, :preview_index, :preview_introduction, :count_page
  ]

  # Cookbook must not be locked for printing
  before_filter :cookbook_locked_for_printing?, except: [:index, :new, :select, :preview]

  # List all cookbooks user has access to.
  def index
    @page_title = "Welcome, #{current_user.first_name}! Let's Get Cooking..."
    @info_panel_title = "Membership info"
    @user = current_user
    @cookbooks = @user.owned_cookbooks
    @contributed_cookbooks = @user.contributed_cookbooks
    @completed_orders = @user.completed_orders
  end

  # Select a cookbook to work on.
  # Alert the user if the cookbook owner account has expired.
  def select
    @cookbook = Cookbook.find params[:id]
    user_is_owner = current_user.owns_cookbook(@cookbook)
    user_is_contributor = current_user.contributes_to(@cookbook)

    # Verify the user is authorized to work on this cookbook.
    if @cookbook && (user_is_owner || user_is_contributor)
      
      # User must have a paid account to work on its cookbooks
      # (Contributor wasn't allowed to create cookbooks but due to a bug some contributors may have cookbooks to works on)
      if has_contributor_plan? && user_is_owner
        redirect_to upgrade_account_path(current_user.id), alert: "You must have a paid membership to work on your own cookbooks"
        return
      end

      load_user_cookbook @cookbook

      # Alert the user it will not be able to work on this cookbook if its owner has expired.
      if current_cookbook.owner.expired?
        if user_is_owner
          flash[:alert]  = "Because your membership has expired you can no longer work on your cookbooks."
        elsif user_is_contributor
          flash[:alert]  = "The owner of this cookbook's membership has expired. They will have to extend it for you to gain access to this cookbook."
        end
      end
      redirect_to templates_path
    else
      redirect_to cookbooks_path, alert: "Unable to select cookbook. Either it doesn't exist or you have no permission accessing it."
    end
  end

  # Create a new cookbook.
  # The cookbook is created automatically and assigned as the current cookbook.
  def new
    cookbook_id = current_user.create_cookbook
    if cookbook_id
      @cookbook = Cookbook.find cookbook_id
      load_user_cookbook @cookbook
      redirect_to templates_path, notice: "A new cookbook was created for you."
    else
      redirect_to upgrade_account_path(current_user.id), alert: "You must have a paid membership to work on your own cookbooks"
    end
  end

  # Edit the cookbook informations
  # Respond with a content type of plain/text to support IE and Opera
  # see: https://github.com/blueimp/jQuery-File-Upload/wiki/Setup#content-type-negotiation
  def edit
    @cookbook = current_cookbook
  end

  # Update the cookbook attributes.
  def update
    @cookbook = current_cookbook

    # Process Paperclip attachments
    @cookbook.process_attachments(params)
    
    if @cookbook.update_attributes_individually params[:cookbook]
      flash[:notice] = 'The template was updated.'
    end
    respond_to do |format|
      format.js { render :update, content_type: "text/plain" }
    end
  end

  # Edit the cookbook title.
  def edit_title
    @cookbook = current_cookbook
  end

  # Update the cookbook title
  def update_title
    @cookbook = current_cookbook
    @cookbook.title = params[:cookbook][:title]
    if @cookbook.save
      redirect_to templates_path, notice: "Your Cookbook name has been changed!"
    else
      render :edit_title
    end
  end

  # Edit the cookbook introduction
  def edit_introduction
    @cookbook = current_cookbook
  end

  # Update introduction elements
  # Respond with a content type of plain/text to support IE and Opera
  # see: https://github.com/blueimp/jQuery-File-Upload/wiki/Setup#content-type-negotiation
  def update_introduction
    @cookbook = current_cookbook

    # Process Paperclip attachments
    @cookbook.process_attachments(params)

    if params[:cookbook]
      @cookbook.intro_type = params[:cookbook][:intro_type] if params[:cookbook][:intro_type]
      @cookbook.center_introduction = params[:cookbook][:center_introduction] if params[:cookbook][:center_introduction]
      @cookbook.intro_text = params[:cookbook][:intro_text] if params[:cookbook][:intro_text]
      @cookbook.intro_image_grayscale = params[:cookbook][:intro_image_grayscale] if params[:cookbook][:intro_image_grayscale]
      @cookbook.intro_image = params[:cookbook][:intro_image] if !params[:cookbook][:intro_image].nil?

      # If the user has checked the "Do not include this page" checkbox, set the intro_type do '2'
      @cookbook.intro_type = 2 if params[:do_not_include]
      @cookbook.intro_type = 0 if !params[:do_not_include] && @cookbook.intro_type == 2
    end

    if @cookbook.save
      flash[:notice] = 'The introduction of your cookbook was saved.'
    end
    respond_to do |format|
      format.js { render :update_introduction, content_type: "text/plain" }
    end
  end

  # Display the cookbook price
  def check_price
    @num_cookbooks = (params[:num_cookbooks] && params[:num_cookbooks].to_i > 3) ? params[:num_cookbooks].to_i : 4
    ccc = CookbookCostCalculator.new(
      num_bw_pages: current_cookbook.num_bw_pages, 
      num_color_pages: current_cookbook.num_color_pages, 
      num_books: @num_cookbooks, 
      binding: current_cookbook.book_binding.to_sym
    )
    @cookbook = current_cookbook
    @printing_cost = ccc.printing_cost || "Unknown"
    @cost_per_book = (@printing_cost != "Unknown") ? (@printing_cost.to_f / @num_cookbooks).round(2) : "Unknown"
  end

  # Preview the cookbook
  # This can be the current cookbook or a cookbook of another person if an order has been created (guest order)
  def preview
    order = current_user.orders.find_by_cookbook_id(params[:id])
    @cookbook = (order) ? order.cookbook : current_cookbook
    preview_path = "#{PDF_PREVIEW_FOLDER}/preview_cookbook-#{@cookbook.id}_#{Time.now.to_i}.pdf"
    session[:preview_filename] = preview_path
    preview = CookbookPreviewWorker.new(
      cookbook: @cookbook, 
      filename: preview_path
    )
    preview.cookbook
    render "previews/preview"
  end

  # Preview the cookbook cover
  def preview_cover
    preview_path = "#{PDF_PREVIEW_FOLDER}/preview_cover-#{current_cookbook.id}_#{Time.now.to_i}.pdf"
    session[:preview_filename] = preview_path
    preview = CookbookPreviewWorker.new(
      cookbook: current_cookbook, 
      filename: preview_path
    )
    preview.cover
    render "previews/preview"
  end

  # Preview the title and the table of contents pages
  def preview_title_and_toc
    preview_path = "#{PDF_PREVIEW_FOLDER}/preview_title_toc-#{current_cookbook.id}_#{Time.now.to_i}.pdf"
    session[:preview_filename] = preview_path
    preview = CookbookPreviewWorker.new(
      cookbook: current_cookbook, 
      filename: preview_path
    )
    preview.title_and_toc
    render "previews/preview"
  end

  # Preview the index page
  def preview_index
    preview_path = "#{PDF_PREVIEW_FOLDER}/preview_index-#{current_cookbook.id}_#{Time.now.to_i}.pdf"
    session[:preview_filename] = preview_path
    preview = CookbookPreviewWorker.new(
      cookbook: current_cookbook, 
      filename: preview_path
    )
    preview.index
    render "previews/preview"
  end

  # Preview the introduction
  def preview_introduction
    preview_path = "#{PDF_PREVIEW_FOLDER}/preview_introduction-#{current_cookbook.id}_#{Time.now.to_i}.pdf"
    session[:preview_filename] = preview_path
    preview = CookbookPreviewWorker.new(
      cookbook: current_cookbook, 
      filename: preview_path
    )
    preview.introduction
    render "previews/preview"
  end

  # Respond with the number of pages for the current cookbook
  def count_page
    num_pages = current_cookbook.num_pages
    render json: {num_pages: num_pages}
  end
end

app/helpers/admin/cookbooks_helper.rb
module Admin::CookbooksHelper
end

app/helpers/cookbook_helper.rb
module CookbookHelper
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/views/cookbooks/_cookbooks_list.html.haml
%ul#cookbooks
  - cookbooks.each do |cookbook|
    %li.cookbook{class: (current_cookbook && current_cookbook.id == cookbook.id) ? "current" : nil, title: (display_cookbook_author) ? "#{cookbook.owner.name}'s #{cookbook.title}" : cookbook.title}
      .template-thumb
        = link_to image_tag((cookbook.template) ? cookbook.template.thumbnail_image : "template_placeholder.gif"), select_cookbook_path(cookbook.id)
        .note= cookbook.title
  - if display_new_cookbook_button
    %li.cookbook
      .template-thumb
        %a#create-a-cookbook-button{href: new_cookbook_path, alt: "Create a new cookbook"}
          #plus +
          New Cookbook

app/views/cookbooks/_modal_help_designing_your_own_cover.html.haml
%h3 Help

.help-text

  %p.note
    %strong THE FOLLOWING IS IMPORTANT

  %p.note When making the cover (and title page) it is important to know that the book is 6x9”  or 7x10” (depending on the binding you chose) and the cover has a 1/2” white border all around. The image/design you create should therefore measure 5x8”, or 6x9” (for the larger 7x10” book).

  %p.note If you would like your cover image to go right to the edge (full bleed), you can make a note of that when you place the order. We can only offer full bleeds on the cover.

  %p.note You can use a photo from your computer or scan an image. Anything scanned should be at a resolution of 250-300 dpi (dots per inch). Anything larger just makes your file too big and won’t improve the quality of the final image.

  %p.note You’ll need to add the text directly to your image before you upload it onto the cover. There are lots of great photo-editing sites online you can use to do this.

  %p.note When you click on the PREVIEW COVER, you may see a wider border at the bottom than on the other three sides; you need to make your image a bit thinner by shaving off some of the sides. The same guidelines apply for the title page, and section dividers you create later on in the book.

= link_to "Close", "#", class: 'close-modal button blue'

app/views/cookbooks/_overview_contributed_to_cookbook.html.haml
- # Display actions and informations for contributors
%li
  Cook Master: 
  = mail_to @cookbook.owner.name, @cookbook.owner.email
%li
  Recipes:
  %br
  = "Currently there are #{pluralize(@cookbook.recipes.count, 'recipe')} in #{pluralize(@cookbook.num_sections_with_recipes, 'section')}."
  %br
  = "You have contributed #{pluralize(@cookbook.num_recipes_contributed_by(@user.id), 'recipe')} and #{pluralize(@cookbook.num_extra_pages_contributed_by(@user.id), "extra page")}."
  %br
  = link_to "Manage Recipes", "#"

app/views/cookbooks/_overview_owned_cookbook.html.haml
- # Display actions and informations for cookbook owners
%li= link_to "Rename this cookbook", edit_title_cookbook_path(@cookbook.id)
%li
  %b Design:
  - if @cookbook.template 
    = @cookbook.template.name 
  - else
    %i= "Design is not set"
  %br
  = link_to (@cookbook.template) ? "Edit Design" : "Choose Design", "#"
%li
  %b Introduction:
  - if (@cookbook.intro_text && !@cookbook.intro_text.empty?) 
    = truncate(@cookbook.intro_text, length: 45) 
  - else 
    %i= "Your introduction text is not set"
  %br
  = link_to "Edit Introduction", show_introduction_cookbook_path(@cookbook)
%li
  %b Contributors:
  - if @cookbook.contributors.empty?
    %i You don't have any contributors
  - else
    = contributors_list @cookbook.contributors
%li
  %b Recipes:
  = "Currently you have #{pluralize(@cookbook.recipes.count, 'recipe')} in #{pluralize(@cookbook.num_sections_with_recipes, 'section')}."
  - if !@cookbook.contributors.empty?
    %br
    = "Out of those, #{pluralize(@cookbook.num_recipes_not_contributed_by(@user.id), "recipe")} were added by your contributors."
  %br
    = link_to "Manage Recipes", "#"

app/views/cookbooks/check_price.html.haml
- content_for :page_title, "Check my book price"
- content_for :headline, "Check my book price"
- content_for :info_panel, render("info_panels/sections")

%h3 Check my Book price

%table.order.pages
  %tr
    %th Book Binding
    %td= @cookbook.book_binding
  %tr
    %th Cover pages (front and back)
    %td 2 pages
  %tr
    %th Color pages
    %td= "#{@cookbook.num_color_pages} pages"
  %tr
    %th Black and white pages
    %td= "#{@cookbook.num_bw_pages} pages"
  %tr
    %th 
      %strong Total pages
    %td 
      %strong= "#{@cookbook.num_pages} pages"
  %tr
    %th 
      %strong Quantity
    %td 
      #num-cookbooks-field{'data-url' => check_price_cookbook_path(current_cookbook)}
        = text_field_tag :num_cookbooks, @num_cookbooks
        %strong cookbooks
%table.order
  %tr
    %th Printing cost per book
    %td= "$ #{@cost_per_book}"
  %tr
    %th 
      %strong Total printing cost
    %td
      %strong= "$ #{@printing_cost}"

%p.note
  Please note shipping is not included in this price. 
  %br 
  To check shipping costs, click the 
  = link_to "Preview and Order", new_order_path
  tab.

= link_to "Return", sections_path, class: "button blue"

app/views/cookbooks/edit.html.haml
- content_for :page_title, "Add photos and text to your cover"
- content_for :headline, "Add photos and text to your cover"
- content_for :info_panel, render("info_panels/design_step_2")

= render "layouts/design_steps"

#template-thumb
  = image_tag @cookbook.template.thumbnail_image

#forms
  #form-errors= errors_for @cookbook if @cookbook.errors.any?
  
  = form_for @cookbook do |f|

    - if @cookbook.template.tag_lines > 0       
      %h3 Personalize your cover text
      - @cookbook.template.tag_lines.times do |number|
        .one-line-controls
          = f.label "tag_line_#{number+1}".to_sym, "Line #{number+1}:"
          = f.text_field "tag_line_#{number+1}".to_sym

    - if @cookbook.template.has_image > 0
      %h3 Upload your own photo
      = f.paperclip_attachment :user_image, image_library: true
      = hidden_field_tag "libimage[user_image]"

    - if !@cookbook.template.cover_image
      %h3 Upload your own cover image
      = f.paperclip_attachment :user_cover_image, label: "Upload an image onto the cover page:"
      = hidden_field_tag "libimage[user_cover_image]"

    %ul
      %li= link_to_preview "Preview the Cover", preview_cover_cookbook_url(@cookbook), class: "picto preview"

    - if !@cookbook.template.inner_cover_image
      %h3 Upload your own title page image
      = f.paperclip_attachment :user_inner_cover_image, label: "Upload an image onto the title page:"
      = hidden_field_tag "libimage[user_inner_cover_image]"

    %ul
      %li= link_to_preview "Preview the Title Page and Table of Contents", preview_title_and_toc_cookbook_path(@cookbook), class: "picto preview"


    %h3 Other options

    .one-line-controls
      = f.check_box :grayscale
      = f.label :grayscale, "Convert the title page, table of contents and section dividers to black-and-white"
    .one-line-controls
      = f.check_box :show_index
      = f.label :show_index, "Add an index page at the end of your cookbook"

    %ul
      %li= link_to_preview "Preview the Index Pages", preview_index_cookbook_path(@cookbook), class: "picto preview"
      
  = link_to "Next", edit_introduction_cookbook_path, class: "button orange next-button alert-on-form-errors"

app/views/cookbooks/edit_introduction.html.haml
- content_for :page_title, "Add a personal note at the front of your book"
- content_for :headline, "Add a personal note at the front of your book"
- content_for :info_panel, render("info_panels/design_step_3")

= render "layouts/design_steps"

#form-errors= errors_for @cookbook if @cookbook.errors.any?

= form_for @cookbook, url: update_introduction_cookbook_path(@cookbook) do |f|

  = check_box_tag :do_not_include, "1", (@cookbook.intro_type == 2)
  = label_tag :do_not_include, "I do not wish to include this page"

  %h3 This page will be a:
  .radio
    = f.radio_button :intro_type, 1
    = f.label :intro_type, "Dedication", value: 1
  .radio
    = f.radio_button :intro_type, 0
    = f.label :intro_type, "Introduction", value: 0

  %h3 Add your text:
  = f.text_area :intro_text, class: "book-content"

  %h3 Make the text:
  .radio
    = f.radio_button :center_introduction, false
    = f.label :center_introduction, "Left aligned", value: false
  .radio
    = f.radio_button :center_introduction, true
    = f.label :center_introduction, "Centered", value: true
    
  %h3 Add your own photo

  = f.paperclip_attachment :intro_image, image_library: true
  = hidden_field_tag "libimage[intro_image]"

  .one-line-controls
    = f.check_box :intro_image_grayscale
    = f.label :intro_image_grayscale, "Turn this into a black-and-white photo"

  %ul
    = link_to_preview "Preview this page", preview_introduction_cookbook_path(@cookbook), class: "picto preview"
    
= link_to "Next", contributors_path, class: "button orange next-button alert-on-form-errors"

app/views/cookbooks/edit_title.html.haml
%h3= "Rename my cookbook"

= errors_for @cookbook if @cookbook.errors.any?

= form_for @cookbook, url: update_title_cookbook_path(@cookbook), html: {class: "edit_cookbook_title"} do |f|
  .control-group
    = f.label :title
    = f.text_field :title
  .control-group
    .align-on-labels
    = f.submit "DONE", class: "orange"
    = link_to "Cancel", :back, class: "button blue"

app/views/cookbooks/index.html.haml
- content_for :page_title, "Welcome, #{current_user.first_name}!"
- content_for :headline, "Welcome, #{current_user.first_name}!"
- content_for :info_panel, render("info_panels/cookbooks")

- # Display user cookbooks
%h3 Here are the cookbooks you are working on:
= render 'cookbooks_list', cookbooks: @cookbooks, display_new_cookbook_button: true, display_cookbook_author: false

- # Display cookbooks user contributed to
- if @contributed_cookbooks.any?
  %h3 Here are the cookbooks you are contributing to:
  = render 'cookbooks_list', cookbooks: @contributed_cookbooks, display_new_cookbook_button: false, display_cookbook_author: true

- if @completed_orders.any?
  %h3= "Here are the completed cookbooks you have ordered (#{@completed_orders.count}):"
  %table#completed-orders-list
    - @completed_orders.each do |order|
      %tr
        %td
          %em= order.generated_at.to_formatted_s(:long_ordinal)
          %br
          %strong= order.cookbook.title
        %td
          = "#{order.number_of_books} books "
          - if order.order_color_pages && order.order_bw_pages
            ="(#{order.num_pages} pages)"
          %br
          = "$ #{(order.order_printing_cost + order.order_shipping_cost).round(2)}"
        %td.actions
          = link_to "re-order", reorder_order_path(order.id), class: "button blue"