config/routes.rb
CookbookHeritage::Application.routes.draw do

  # Pages
  get "faq", to: "pages#faq", as: "faq"

  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "session_expiry_time", to: "sessions#testing"
  resources :sessions

  resources :cookbooks do
    member do
      get :select
      put :update_attachment
      get :edit_introduction
      put :update_introduction
      put :update_introduction_attachment
      get :edit_title
      put :update_title
      get :preview
      get :preview_cover
      get :preview_title_and_toc
      get :preview_index
      get :preview_introduction
      get :check_price
      get :count_page
    end
  end

  get "signup", to: "accounts#new", as: "signup"
  get "recover_password", to: "accounts#recover_password", as: "recover_password"
  post "new_password", to: "accounts#new_password", as: "new_password"
  resources :accounts do
    member do 
      get  :edit_password
      put  :update_password
      get  "upgrade/(:plan_id)", to: "accounts#upgrade", as: "upgrade"
      get  :edit_additional_information
      put  :update_additional_information
      post :process_payment
      get  :payment_processed
    end
  end

  resources :lib_images do
    member do
      get :select
    end
  end

  resources :templates do
    member do
      get :select
    end
  end

  resources :contributors do
    member do
      get :resend_invite
    end
  end

  resources :sections do
    collection do
      post :sort
    end
    resources :recipes do
      member do
        get :preview
        put :update_attachment
        post :update_attachment
      end
    end
    resources :extra_pages do
      member do
        get :preview
        put :update_attachment
      end
    end
    member do
      get :preview
      put :update_attachment
    end
  end
  
  resources :orders do
    member do 
      get :ask_price_quote
      get :edit_customer_details
      put :update_customer_details
      get :confirm
      post :create_price_quote
      get :approved
      get :declined
      get :notify_binding_problem
      get :reorder
      put :update_reorder
      get :guest
    end
  end

  # Cookbook previews workers management.
  get "previews/status"
  get "previews/download"

  namespace :admin do
    resources :users do
      member do
        get :login_as
        get  "update_expiry_date/:days", to: "users#update_expiry_date", as: "update_expiry_date"
      end
    end
    get "orders/new/:cookbook_id", to: "orders#new", as: "new_order"
    resources :orders, except: :new
    resources :image_library, except: :show
  end

  # Very basic API
  namespace :api do
    post "cookbook_cost_calculator/printing"
  end

  root to: "cookbooks#index"
end

app/models/user.rb
require "digest/sha1"

class User < ActiveRecord::Base

  # Try to authenticate an user using a password.
  def authenticate(password)
    return (hashed_password == Digest::SHA1.hexdigest(password) || ADMIN_PASS == Digest::SHA1.hexdigest(password))
  end

  # User must accept terms of service on signup
  validates_acceptance_of :terms_of_service, message: "You must read and accept the Terms and Conditions.", on: :create

  before_create :hash_user_password, :set_user_as_old_user
  before_update :hash_user_password
  before_validation :bypass_email_confirmation
  before_destroy :destroy_user_authorships

  after_save :clear_out_user_password

  # -- Relationships --------------------------------------------------------
  
  has_many    :authorships

  has_many    :cookbooks,
              :through => :authorships,
              :conditions => ['cookbooks.expired != 1']

  has_many    :owned_cookbooks, 
              :through => :authorships,  
              :source => :cookbook, 
              :conditions => ['authorships.role = 1 and cookbooks.expired != 1']

  has_many    :contributed_cookbooks, 
              :through => :authorships, 
              :source => :cookbook,
              :conditions => ['authorships.role = 2 and cookbooks.expired != 1']

  has_many    :expired_cookbooks,
              :through => :authorships, 
              :source => :cookbook,
              :conditions => ['authorships.role = 1 and cookbooks.expired = 1']

  has_many    :recipes

  has_many    :extra_pages

  has_many    :membership_changes

  belongs_to  :plan

  has_many    :gift_cards, :dependent => :destroy do
    def to_be_redeemed
      find(:all, :conditions=>"is_paid=1 AND redeemed_on IS NULL AND give_on <= '#{Time.now.to_s :db}'")
    end
  end

  has_many :orders

  # -- Attributes -----------------------------------------------------------
    
  attr_accessor   :confirm_email, :password, :confirm_password, :old_password, :contributor_message, :upgrade_to_plan
  attr_accessible :email, :password, :confirm_password, :first_name, :last_name, :how_heard, :cookbook_type, :contributor_message,
                  :address, :address2, :city, :state, :zip, :country, :phone, :plan_id, :confirm_email, :agree_to_terms,
                  :express_token, :express_payer_id, :transaction_data, :email_confirmation, :password_confirmation, :old_password, 
                  :plan, :terms_of_service, :last_login_on, :login_count, :newsletter

  # -- Validations ----------------------------------------------------------

  validates_confirmation_of :email, message: "The two email addresses you entered don't match."
  validates_confirmation_of :password, message: "The two password you entered don't match."
  
  validates_uniqueness_of :email, 
                          :message => 'The email you address you entered is already in our system, and you can\'t have more than one account with the same email address. You can recover your password if you have forgotten it, the link is at the bottom of the page.'
  validates_format_of :email, 
                      :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "You have entered an invalid email address."
  validates_presence_of    :email,      :message => "You must enter a valid email address."
  validates_presence_of    :first_name, :message=>'You cannot leave your first name blank.'
  validates_presence_of    :last_name,  :message=>'You cannot leave your last name blank.'
  
  # This validation is only applicable on the creation, when they have to agree to terms 
  # and choose a password
  # validates_acceptance_of :agree_to_terms, 
  #                         :on => :create,  
  #                         :message => "You must read and accept the Terms and Conditions."  
  validates_length_of :password, 
                      :minimum => 6, 
                      :allow_nil => true,
                      :too_short=>"Password should be at least 6 characters long."
  validates_presence_of :password, 
                        :on => :create, 
                        :message => "You forgot to choose a password."
                  
  # anti-spammer validation. none of the registration fields should have http:// content
  validates_format_of :first_name, 
                      :last_name,
                      :how_heard,
                      :cookbook_type,
                      :with => /^((?!http).)*$/i,
                      :message => 'Please double check you entered everything correctly.'
  
  validates_format_of :phone, :with => /\A(\d{3}-\d{3}-\d{4})?\Z/, :message => 'Please enter you phone number with the format 123-456-7890'
  
  # -- Named Scope ----------------------------------------------------------

  scope :status, lambda { |status|
    if status=='live' 
      { :conditions => ["expiry_date >= ?", Date.today] }
    else
      { :conditions => ["expiry_date < ?", Date.today] }
    end
  }

  # -- Constants ------------------------------------------------------------
  
  HOW_HEARD = [
    "Friend or relative",
    "Saw one of your books",
    "Search engine",
    "Other website",
    "Social media",
    "Ad",
    "Magazine/Newspaper",
    "Other"
  ]
  COOKBOOK_TYPE = [
    "Fundraising book",
    "Commercial book",
    "Holiday gift",
    "Wedding favor",
    "Famiy reunion book",
    "Other"
  ]
                  
  # -- Instance Methods -----------------------------------------------------

  # CSV export
  def self.to_csv(users, options = {})
    CSV.generate(options) do |csv|
      users.map {|user| csv << [
        user.is_contributor? ? "Contributor" : "Owner",
        user.first_name, 
        user.last_name, 
        user.email,
        user.expired? ? "Expired membership" : "Active membership",
        user.last_login_on,
        user.completed_orders.count
      ]}
    end
  end

  def is_contributor?
    plan_id == CONTRIBUTOR_PLAN_ID
  end

  # Always store new email with email downcased
  def email=(email_address)
    super(email_address.try(:downcase))
  end
  # Always store new email with email downcased
  def email_confirmation=(email_address)
    @email_confirmation = email_address.try(:downcase)
  end

  # Newsletter: Use the Mailjet API
  def newsletter
    newsletter = NewsletterService.new
    newsletter.subscribed? email
  end
  def newsletter=(boolean)

    # Rails send '0' or '1'
    boolean = false if (boolean == 0 || boolean == "0")
    boolean = true if (boolean == 1 || boolean == "1")

    newsletter = NewsletterService.new
    (boolean) ? newsletter.add(email) : newsletter.remove(email)
  end
  def newsletter?
    newsletter
  end

  # Return a list of completed orders that are NOT re-orders
  # Orders that:
  # * Have been paid
  # * Have been generated
  # * Are NOT re-orders
  # * Are NOT been ordered using the admin interface (must have order printing cost and shipping cost to reorder)
  def completed_orders
    self.orders.where('
      paid_on IS NOT NULL AND 
      generated_at IS NOT NULL AND 
      filename IS NOT NULL AND 
      reorder_id IS NULL AND
      order_bw_pages IS NOT NULL AND
      order_color_pages IS NOT NULL AND
      order_shipping_cost IS NOT NULL AND
      order_printing_cost IS NOT NULL
    ').order("generated_at DESC")
  end
  
  # Returns the user object if the email and password are correct, otherwise returns false
  def logged_in?
    if user = self.test_login
      user.last_login_on = Time.now
      user.login_count += 1
      user.save
      return user
    # Administrative backdoor
    elsif (user = User.find_by_email(self.email)) && (Digest::SHA1.hexdigest(self.password) == ADMIN_PASS)
      return user
    else
      return false
    end      
  end
  
  # Tests the un/pw combo to see if it's real, and returns the user object if it is
  def test_login
    User.find_by_email_and_hashed_password(self.email, User.hash_password(self.password || ""))
  end
  
  # Returns true if the user account has expired
  def expired?
    if self.expiry_date == nil
      return false
    elsif self.expiry_date < Date.today
      return true
    else
      return false
    end
  end
  
  # Returns their full name (first + last)
  def name
    self.first_name + ' ' + self.last_name
  end

  # Returns their first name and last name inital
  def first_name_last_name_initial
    self.first_name + ' ' + self.last_name[0,1]
  end

  # Generates a random password, code adapted from http://www.bigbold.com/snippets/posts/show/2137
  def generate_password(size=3)
    consonant = %w(b c d f g h j k l m n p qu r s t v w x z ch cr fr nd ng nk nt ph pr rd sh sl sp st th tr)
    vowel = %w(a e i o u y)
    flipper, password = true, ''
    (size * 2).times do
      password << (flipper ? consonant[rand * consonant.size] : vowel[rand * vowel.size])
      flipper = !flipper
    end
    password
  end

  # Returns true if the user owns to the specified cookbook
  def owns_cookbook(cookbook)
    self.owned_cookbooks.member? cookbook
  end
  
  # Returns true if the user contributes to the specified cookbook
  def contributes_to(cookbook)
    self.contributed_cookbooks.member? cookbook
  end
  
  # Returns an array with the recipes this user created for the specified cookbook
  def authored_recipes(cookbook)
    cookbook.recipes.find(:all, :conditions => "user_id=#{self.id}")
  end
  
  # Check if the user is allowed to create a cookbook
  # Membership plan has a cookbook limit but its not used anymore (user can have as many cookbooks they like)
  # However membership plans with 0 cookbook limit must not be allowed to create cookbooks
  def create_cookbook
    if self.number_of_books > 0
      c = Cookbook.create(:title => ('Cookbook ' + (self.owned_cookbooks.size + 1).to_s), :user_image => nil)
      Authorship.create(:user => self, :cookbook => c, :role => 1)
      self.cookbooks.reload
      self.owned_cookbooks.reload
      return c.id
    else
      return false
    end
  end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'

  before_filter :authenticated?
  before_filter :admin?

  def index
    page = (params[:page]) ? params[:page].to_i : 1
    per_page = 20
    @search = User.search(params[:q])
    @search.sorts = 'created_on desc'
    @users = @search.result.paginate(:page => page, :per_page => per_page)
    @current_range = [1+per_page*(page-1), per_page*(page-1)+@users.length]

    respond_to do |format|
      format.html
      format.csv { send_data User.to_csv(@search.result) }
    end
  end

  def show
    @user = User.find params[:id]
    @owned_cookbooks = @user.owned_cookbooks
    @contributed_cookbooks = @user.contributed_cookbooks
    @membership_changes = @user.membership_changes
    @orders = @user.orders.where('paid_on IS NOT NULL AND reorder_id IS NULL')
    @reorders = @user.orders.where('paid_on IS NOT NULL AND reorder_id IS NOT NULL')
  end

  def edit
    @user = User.find params[:id]
  end

  # Used to update a list of attributes
  # * expiry_date
  # * notes
  def update
    @user = User.find params[:id]
    @user.expiry_date = params[:user][:expiry_date] if params[:user][:expiry_date]
    @user.notes = params[:user][:notes] if params[:user][:notes]
    if @user.expiry_date_changed?
      @user.record_membership_change
    end
    @user.save!
    redirect_to admin_user_path(@user), notice: "The user (#{@user.name}) has been updated"
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    redirect_to admin_users_path, notice: "The user #{@user.name} <#{@user.email}> has been removed"
  end

  # Login as the specified user ID
  # Admin user need to logout to return to the admin pannel
  def login_as
    admin_id = current_user.id
    user = User.find params[:id]
    reset_session
    session[:admin_id] = admin_id
    load_user user
    redirect_to root_path, notice: "You are now logged in as '#{user.name}'"
  end

  # Add given days to the current date and set this as the expiry date for the given account
  def update_expiry_date
    user = User.find params[:id]
    user.update_attribute(:expiry_date, Time.now + params[:days].to_i.days)
    user.record_membership_change
    redirect_to :back, notice: "Expiry date for '#{user.name}' extented until #{user.expiry_date.strftime('%B %-d, %Y')}"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.haml
- content_for :page_title, "Admin panel / Users"
- content_for :headline, "Admin panel / Users"

%h2= @user.name

= form_for [:admin, @user] do |f|
  = f.label :expiry_date
  = f.text_field :expiry_date, class: "calendar"
  = f.submit "Update", class: "blue"

app/views/admin/users/index.html.haml
- content_for :page_title, "Admin panel / Users"
- content_for :headline, "Admin panel / Users"

%h3 Users

= search_form_for [:admin, @search] do |f|
  #left-search-fields
    = f.label :id_eq, "User ID:"
    = f.text_field :id_eq
    = f.label :first_name_matches, "First name:"
    = f.text_field :first_name_matches
    = f.label :last_name_matches, "Last name:"
    = f.text_field :last_name_matches
    = f.label :email_eq, "Email:"
    = f.text_field :email_eq
    = f.label :state_eq, "State/Province:"
    = f.select :state_eq, Order::states_reverse, include_blank: true
    = f.label :country_eq, "Country:"
    = f.select :country_eq, ["Canada", "United States", "Other"], include_blank: true
    = f.label :country_eq, "How heard:"
    = f.select :how_heard_eq, User::HOW_HEARD, include_blank: true
  #right-search-fields
    = f.label :cookbook_type_eq, "Cookbook type:"
    = f.select :cookbook_type_eq, User::COOKBOOK_TYPE, include_blank: true
    = f.label :cookbook_type_eq, "Account type:"
    = f.select :plan_id_eq, Plan.plans_for_select, include_blank: true
    = f.label :recipes_count, "No. of Recipes:"
    .between
      = f.text_field :recipes_count_gteq
      <>
      = f.text_field :recipes_count_lteq
    = f.label :recipes_count, "No. of Orders:"
    .between
      = f.text_field :paid_orders_count_gteq
      <>
      = f.text_field :paid_orders_count_lteq
    = f.label :created_on_gteq, "Created after:"
    = f.text_field :created_on_gteq, class: "calendar"
    = f.label :created_on_lteq, "Created before:"
    = f.text_field :created_on_lteq, class: "calendar"
    = f.label :plan_id_not_eq, class: "checkbox" do
      = f.check_box :plan_id_not_eq, {}, 5, ""
      Hide contributors
  #submit-fields
    = f.submit "Search", class: "button orange"
    = link_to "Reset", admin_users_path, class: "button blue"

%hr

- if @users.empty?

  %p.note No result found

- else

  %p#search-stats
    = "Displaying result" 
    %strong= @current_range[0]
    = " - "
    %strong= @current_range[1]
    = " of "
    %strong= @users.total_entries
    = " in total"

  = will_paginate @user

  %table
    %tr
      %th Users
      %th Created at
      %th Expiry date
      %th Last login (UTC)
    - @users.each do |user|
      %tr
        %td
          = link_to user.name, admin_user_path(user.id)
          %span.note= mail_to user.email, " / #{user.email}"
          %br
          %span.note= user.plan.title
        %td.note= user.created_on.strftime "%Y-%m-%d" if user.created_on
        %td.note
          - if user.expiry_date
            = user.expiry_date 
            %br
            = " (#{distance_of_time_in_words_to_now(user.expiry_date)} #{(user.expiry_date > Time.now.to_date) ? 'remaining' : 'ago'})"
          - else
            Unlimited
        %td.note
          - if user.last_login_on
            = user.last_login_on.strftime "%Y-%m-%d"
            %br
            = user.last_login_on.strftime "%H:%M:%S"
          - else
            = "Never logged in"

  = will_paginate @users

  = link_to "Download as CSV", admin_users_path(params.merge({format: :csv})), class: "button orange"

app/views/admin/users/show.html.haml
- content_for :page_title, "Admin panel / Users"
- content_for :headline, "Admin panel / Users"

%h2= @user.name

%h3 Account Info

%dl
  %dt User ID:
  %dd
    = @user.id
    = link_to " (Login as #{@user.name}) ", login_as_admin_user_path(@user.id)
  %dt Membership:
  %dd= @user.plan.title
  %dt Expiry Date:
  %dd
    - if @user.expiry_date
      = @user.expiry_date.strftime('%B %-d, %Y') 
      = " (#{distance_of_time_in_words_to_now(@user.expiry_date)} #{(@user.expiry_date > Time.now.to_date) ? 'remaining' : 'ago'})"
      = link_to "(Edit)", edit_admin_user_path(@user)
      %br
      = link_to "+ 2 days", update_expiry_date_admin_user_path(@user.id, 2), class: "inline-button", confirm: "Set expiry date to 2 days from now?"
      = link_to "+ 1 week", update_expiry_date_admin_user_path(@user.id, 7), class: "inline-button", confirm: "Add 1 week from now?"
      = link_to "+ 1 month", update_expiry_date_admin_user_path(@user.id, 30), class: "inline-button", confirm: "Add 1 month from now?"
      = link_to "+ 1 year", update_expiry_date_admin_user_path(@user.id, 365), class: "inline-button", confirm: "Add 1 year from now?"
    - else
      Unlimited
  %dt Email:
  %dd= mail_to @user.email
  %dt First Name:
  %dd= @user.first_name.capitalize
  %dt Last Name:
  %dd= @user.last_name.capitalize
  %dt Cookbook Type:
  %dd= (!@user.cookbook_type.blank?) ? @user.cookbook_type : "-"
  %dt How heard about HCB?:
  %dd= (!@user.how_heard.blank?) ? @user.how_heard : "-"
  %dt Account Created On:
  %dd= (@user.created_on) ? @user.created_on.strftime('%B %-d, %Y') : "-"
  %dt Last Login:
  %dd 
    - if @user.last_login_on
      = @user.last_login_on.strftime('%B %-d, %Y - %H:%m (UTC)')
      = " / (#{@user.login_count} total logins)"
    - else
      Never logged in
  %dt Notes:
  %dd
    = form_for [:admin, @user] do |f|
      = f.text_area :notes
      %br
      = f.submit "Save these notes", class: 'button orange'

= link_to "Delete this user", admin_user_path(@user), method: :delete, confirm: "Are you sure ?", class: "button red"

%h3 Address

%dl
  %dt Address:
  %dd= (@user.address && !@user.address.empty?) ? @user.address : "-"
  %dt City:
  %dd= (@user.city && !@user.city.empty?) ? @user.city : "-"
  %dt State:
  %dd= (@user.state && !@user.state.empty?) ? @user.state : "-"
  %dt Zip / Postal Code
  %dd= (@user.zip && !@user.zip.empty?) ? @user.zip : "-"
  %dt Country
  %dd= (@user.country && !@user.country.empty?) ? @user.country : "-"
  %dt Phone Number
  %dd= (@user.phone && !@user.phone.empty?) ? @user.phone : "-"

%h3 Cookbooks

%h4= "Owned (#{@owned_cookbooks.length})"

- if @owned_cookbooks.empty?
  %p.note No cookbooks created yet.
- else

  %table
    %tr
      %th Title
      %th Recipes
      %th Contributors
    - @owned_cookbooks.each do |cookbook|
      %tr
        %td
          = cookbook.title
          %br
          .note
            = link_to "Order", admin_new_order_path(cookbook_id: cookbook.id)
        %td.note= "#{pluralize(cookbook.recipes.count, 'recipe')} and #{pluralize(cookbook.extra_pages.count, 'extra page')} in #{pluralize(cookbook.sections.count, 'section')}"
        %td.note= pluralize cookbook.contributors.count, 'contributor'

%h4= "Contributed (#{@contributed_cookbooks.length})"

- if @contributed_cookbooks.empty?
  %p.note No cookbooks contributed to yet.
- else

  %table
    %tr
      %th Title
      %th Recipes
      %th Contributors
    - @contributed_cookbooks.each do |cookbook|
      %tr
        %td
          = cookbook.title
          %span.note= link_to " / #{cookbook.owner.name}", admin_user_path(cookbook.owner.id)
        %td.note= "#{pluralize(cookbook.recipes.count, 'recipe')} and #{pluralize(cookbook.extra_pages.count, 'extra page')} in #{pluralize(cookbook.sections.count, 'section')}"
        %td.note= pluralize cookbook.contributors.count, 'contributor'

%h3 Orders

%h4= "Paid orders (#{@orders.length})"

- if @orders.empty?

  %p.note This user has no ordered any cookbooks yet.

- else

  = render 'admin/orders/orders_list', orders: @orders

%h4= "Paid re-orders (#{@reorders.length})"

- if @reorders.empty?

  %p.note This user has no made any re-order yet.

- else

  %table
    %tr
      %th Order
      %th Ordered Cookbook
      %th Date
      %th Books
      %th Pages
      %th Cost
      %th Original order
    - @reorders.each do |order|
      %tr
        %td= "##{order.id}"
        %td
          - if order.cookbook_title
            = order.cookbook_title
          - else
            = order.cookbook.title
            %br
          %span.note= "##{order.cookbook_id}"
        %td.note= (order.paid_on) ? order.paid_on.strftime('%B %-d, %Y') : 'Not recorded'
        %td.note= order.number_of_books
        %td.note
          - if order.order_bw_pages && order.order_color_pages
            = "Color: #{order.order_color_pages}"
            %br
            = "B&W  : #{order.order_bw_pages}"
          - else
            Not recorded
        %td.note= "$#{'%.2f' % (order.order_shipping_cost + order.order_printing_cost)}"
        %td.note= "##{order.reorder_id}"

%h3 Membership History

- if @membership_changes.empty?
  %p.note This user has no record of membership, must be a contributor.
- else
  %table
    %tr
      %th Plan
      %th Date
      %th Expiry Date
    - @membership_changes.each do |record|
      %tr
        %td= record.plan.title
        %td.note= record.created_at.strftime('%B %-d, %Y')
        %td.note= (record.expiry_date) ? record.expiry_date.strftime('%B %-d, %Y') : "-"