config/routes.rb
CookbookHeritage::Application.routes.draw do

  # Pages
  get "faq", to: "pages#faq", as: "faq"

  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "session_expiry_time", to: "sessions#testing"
  resources :sessions

  resources :cookbooks do
    member do
      get :select
      put :update_attachment
      get :edit_introduction
      put :update_introduction
      put :update_introduction_attachment
      get :edit_title
      put :update_title
      get :preview
      get :preview_cover
      get :preview_title_and_toc
      get :preview_index
      get :preview_introduction
      get :check_price
      get :count_page
    end
  end

  get "signup", to: "accounts#new", as: "signup"
  get "recover_password", to: "accounts#recover_password", as: "recover_password"
  post "new_password", to: "accounts#new_password", as: "new_password"
  resources :accounts do
    member do 
      get  :edit_password
      put  :update_password
      get  "upgrade/(:plan_id)", to: "accounts#upgrade", as: "upgrade"
      get  :edit_additional_information
      put  :update_additional_information
      post :process_payment
      get  :payment_processed
    end
  end

  resources :lib_images do
    member do
      get :select
    end
  end

  resources :templates do
    member do
      get :select
    end
  end

  resources :contributors do
    member do
      get :resend_invite
    end
  end

  resources :sections do
    collection do
      post :sort
    end
    resources :recipes do
      member do
        get :preview
        put :update_attachment
        post :update_attachment
      end
    end
    resources :extra_pages do
      member do
        get :preview
        put :update_attachment
      end
    end
    member do
      get :preview
      put :update_attachment
    end
  end
  
  resources :orders do
    member do 
      get :ask_price_quote
      get :edit_customer_details
      put :update_customer_details
      get :confirm
      post :create_price_quote
      get :approved
      get :declined
      get :notify_binding_problem
      get :reorder
      put :update_reorder
      get :guest
    end
  end

  # Cookbook previews workers management.
  get "previews/status"
  get "previews/download"

  namespace :admin do
    resources :users do
      member do
        get :login_as
        get  "update_expiry_date/:days", to: "users#update_expiry_date", as: "update_expiry_date"
      end
    end
    get "orders/new/:cookbook_id", to: "orders#new", as: "new_order"
    resources :orders, except: :new
    resources :image_library, except: :show
  end

  # Very basic API
  namespace :api do
    post "cookbook_cost_calculator/printing"
  end

  root to: "cookbooks#index"
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController

  # User needs to be authenticated.
  before_filter :authenticated?

  # User need to have a cookbook selected
  before_filter :cookbook_selected?

  # User account must not be expired.
  before_filter :account_expired?

  # User must not be a contributor
  before_filter :cookbook_owner?

  # List all contributors to your cookbooks.
  # Invite new contributors.
  def index
    @contributor = User.new
    @contributors = current_cookbook.contributors
  end

  # Send an invite and enable the contributor account.
  def create
    contributor_email   = params[:user][:email]
    @contributor_message = params[:user][:contributor_message]

    # Verify the user isn't trying to invite himself
    if contributor_email == current_user.email
      redirect_to contributors_path, alert: "You cannot add yourself as a contributor"
      return
    end

    @contributor = User.find_by_email(contributor_email)

    # User add a non-existing user as contributor
    if !@contributor
      @new_contributor = true
      @contributor = User.new_contributor(params[:user])
      @contributor_password = @contributor.password

      if !@contributor.save
        @contributors = current_cookbook.contributors
        render :index
        return
      end
    end

    # Add authorship to the current cookbook
    @authorship = Authorship.new(user: @contributor, cookbook: current_cookbook, role: 2)
    if @authorship.save

      # Send email to the contributor.
      if @new_contributor
        AccountMailer.delay.added_as_new_contributor(@contributor, current_user, @contributor_password, login_url, @contributor_message)
      else
        AccountMailer.delay.added_as_contributor(@contributor, current_user, login_url, @contributor_message)      
      end

      flash[:notice] = "#{@contributor.name} was added to your list of contributors."
    else
      flash[:alert] = "This contributor is already on your list"
    end

    redirect_to contributors_path
  end

  # Resend a contributor invitation.
  def resend_invite
    if User.exists?(params[:id])
      @contributor = User.find params[:id]

      if current_cookbook.is_contributor? @contributor

        # Contributor is a new user, regenerate a password
        if @contributor.login_count == 0
          new_password = @contributor.save_new_password
          AccountMailer.delay.added_as_new_contributor(@contributor, current_user, new_password, login_url)

        # Contributor is an existing user
        else
          AccountMailer.delay.added_as_contributor(@contributor, current_user, login_url)
        end

        flash[:notice] = "Invitational Email to #{@contributor.email} was resent."
      end
    end

    redirect_to contributors_path
  end

  # Remove a contributor.
  def destroy

    if User.exists?(params[:id])
      @contributor = User.find params[:id]

      if current_cookbook.is_contributor? @contributor
        authorship = current_cookbook.authorships.find_by_user_id @contributor.id
        authorship.destroy
        flash[:notice] = "That contributor was removed from your contributor list"
      end
    end

    redirect_to contributors_path
  end
end

app/helpers/contributor_helper.rb
module ContributorHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/views/contributors/index.html.haml
- content_for :page_title, "Invite helpers to work with you"
- content_for :headline, "You don’t have to do it alone!"
- content_for :info_panel, render("info_panels/contributors")


%h3 Invite helpers to work with you

= errors_for @contributor if @contributor.errors.any?

= form_for @contributor, url: contributors_url do |f|
  .control-group
    = f.label :first_name, "First name:"
    = f.text_field :first_name
  .control-group
    = f.label :last_name, "Last name:"
    = f.text_field :last_name
  .control-group
    = f.label :email, "Email address:"
    = f.text_field :email
  .control-group
    = f.label :contributor_message, "Enter a brief message that will be emailed to this person:"
    = f.text_area :contributor_message
  .control-group
    .align-on-labels
    = f.submit "Invite", class: 'blue'


- if @contributors.count > 0
  %hr
  %h3= "Current contributors to your cookbook (#{@contributors.count})"

  %table.contributors
    - @contributors.each do |contributor|
      %tr.contributor
        %td
          .name<
            = "#{contributor.name}"
            %span.email= mail_to contributor.email, "(#{contributor.email})"
          .actions
            = link_to "resend invitation", resend_invite_contributor_path(contributor.id)
            |
            = link_to "remove", contributor_path(contributor.id), method: :delete
        %td.contributed-recipes= "Contributed recipes: #{current_cookbook.num_recipes_contributed_by(contributor.id)}"

= link_to "Next", sections_path, class: "button orange"