config/routes.rb
CookbookHeritage::Application.routes.draw do

  # Pages
  get "faq", to: "pages#faq", as: "faq"

  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "session_expiry_time", to: "sessions#testing"
  resources :sessions

  resources :cookbooks do
    member do
      get :select
      put :update_attachment
      get :edit_introduction
      put :update_introduction
      put :update_introduction_attachment
      get :edit_title
      put :update_title
      get :preview
      get :preview_cover
      get :preview_title_and_toc
      get :preview_index
      get :preview_introduction
      get :check_price
      get :count_page
    end
  end

  get "signup", to: "accounts#new", as: "signup"
  get "recover_password", to: "accounts#recover_password", as: "recover_password"
  post "new_password", to: "accounts#new_password", as: "new_password"
  resources :accounts do
    member do 
      get  :edit_password
      put  :update_password
      get  "upgrade/(:plan_id)", to: "accounts#upgrade", as: "upgrade"
      get  :edit_additional_information
      put  :update_additional_information
      post :process_payment
      get  :payment_processed
    end
  end

  resources :lib_images do
    member do
      get :select
    end
  end

  resources :templates do
    member do
      get :select
    end
  end

  resources :contributors do
    member do
      get :resend_invite
    end
  end

  resources :sections do
    collection do
      post :sort
    end
    resources :recipes do
      member do
        get :preview
        put :update_attachment
        post :update_attachment
      end
    end
    resources :extra_pages do
      member do
        get :preview
        put :update_attachment
      end
    end
    member do
      get :preview
      put :update_attachment
    end
  end
  
  resources :orders do
    member do 
      get :ask_price_quote
      get :edit_customer_details
      put :update_customer_details
      get :confirm
      post :create_price_quote
      get :approved
      get :declined
      get :notify_binding_problem
      get :reorder
      put :update_reorder
      get :guest
    end
  end

  # Cookbook previews workers management.
  get "previews/status"
  get "previews/download"

  namespace :admin do
    resources :users do
      member do
        get :login_as
        get  "update_expiry_date/:days", to: "users#update_expiry_date", as: "update_expiry_date"
      end
    end
    get "orders/new/:cookbook_id", to: "orders#new", as: "new_order"
    resources :orders, except: :new
    resources :image_library, except: :show
  end

  # Very basic API
  namespace :api do
    post "cookbook_cost_calculator/printing"
  end

  root to: "cookbooks#index"
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticated?, except: [:new, :create, :recover_password, :new_password]

  # Display the signup page.
  def new

    # Redirect the user if already logged
    if current_user
      redirect_to root_path
      return
    end
    
    @user = User.new
  end

  # Create an user account.
  # A welcome email is sent with user credentials.
  # If the user signup to a paid membership plan, it will be redirected to the payment page.
  def create

    @user = User.new params[:user]

    if @user.save
      load_user @user
      flash[:notice] = "Congratulations, your Heritage Cookbook account has been created!"
      
      # Once user is saved, `password` and `password_confirmation` must be cleared.
      # By default, `password` is automatically cleared after save but not `password_confirmation`.
      @user.password_confirmation = nil

      # Send an email to the user with its credentials.
      AccountMailer.delay.signup_details(@user, login_url)

      # Put the user on the proper plan and ask for payment if needed.
      is_payment_needed = @user.switch_to_plan params[:user][:plan_id]
      if is_payment_needed
        redirect_to upgrade_account_path(@user, plan_id: params[:user][:plan_id])
      else
        redirect_to root_path
      end
    else
      render :new
    end
  end

  # Upgrade the user account plan.
  def upgrade
    if params[:plan_id]
      @plans_available = Plan.available_signup_plans.reject!{|p| p[1] == 1}
      @plan = Plan.find params[:plan_id]
      @selected_plan = @plan
    else
      @plans_available = Plan.available_upgrade_plans
      @plan = Plan.find @plans_available.first[1]
    end
  end

  # Process account upgrade payment.
  # Allow payment with credit card for non Paypal user.
  def process_payment
    @plan = Plan.find params[:plan]
    session[:purchased_plan_id] = @plan.id

    response = EXPRESS_GATEWAY.setup_purchase(@plan.price_in_cents,
      ip: request.remote_ip, 
      return_url: payment_processed_account_url(current_user),
      cancel_return_url: root_url,
      no_shipping: true,
      description: @plan.title,
      allow_guest_checkout: true,
      brand_name: "Heritage Cookbook"
    )

    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token, review: false)
  end

  # Inform the user on its payment status and update the user membership plan.
  # Send an email to inform opertors.
  def payment_processed
    @plan = Plan.find session[:purchased_plan_id]
    session[:purchased_plan_id] = nil
    @user = current_user

    # Ask confirmation for the purchase
    purchase = EXPRESS_GATEWAY.purchase @plan.price_in_cents,
      ip: request.remote_ip,
      token: params[:token],
      payer_id: params[:PayerID]
    
    if purchase.success?

      # Save payment data for this user
      @user.update_attributes(
        express_token: params[:token], 
        express_payer_id: params['PayerID'],
        transaction_data: EXPRESS_GATEWAY.details_for(params[:token])
      )
      @user.switch_to_plan(@plan.id, true)

      # Inform operators an account has been paid
      AdministrativeMailer.delay.account_upgraded(@user)

      redirect_to root_path, notice: "Your payment was successful and your account has been upgraded."
    else
      redirect_to upgrade_account_path(@user), notice: purchase.message
    end
  end

  # Display the page to edit account informations
  def edit
    @user = current_user
  end

  # Change the account informations.
  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to edit_account_path(current_user), notice: "Your account information was successfully updated."
    else
      render :edit
    end
  end

  # Display the page to update user password.
  def edit_password
    @user = current_user
  end

  # Change the user password.
  # User must provide the valid currrent password before change are saved.
  def update_password
    @user = current_user
    if @user.authenticate params[:user][:old_password]
      if @user.update_attributes params[:user]
        reset_session
        redirect_to login_path, notice: "Your password was successfully changed. Please login with your new password to verify it worked.\nIf you have a problem, you can always get a new password with the \"Forgot your password\" link"
        return
      end
    else
      @user.errors[:old_password] = "Incorrect current password. Changes were not made."
    end
    render :edit_password
  end

  # Page to recover the user password.
  def recover_password
    @user = User.new
  end

  # Reset the user password and send him a new one.
  def new_password
    @user = User.find_by_email(params[:user][:email])
    if @user
      generated_password = @user.generate_password
      if @user.update_attribute :password, generated_password

        # Send the user its new password
        AccountMailer.delay.forgot_password(@user, generated_password)

        redirect_to login_path, notice: 'A new password has been generated for you, and emailed to the email address you entered.'
      else
        render :recover_password
      end
    else
      @user = User.new
      @user.errors[:email] << "Cannot find provided email, or it is incorrectly typed"
      render :recover_password
    end
  end

  # Ask user additionnal informations.
  # Enable newsletter by default.
  def edit_additional_information
    @user = current_user
    @user.newsletter = true
  end

  # Change optional informations.
  def update_additional_information
    @user = current_user
    if @user.update_attributes(params[:user])

      @user.errors[:address] << "Please enter your address"         unless !@user.address.blank?
      @user.errors[:city]    << "Please enter your city"            unless !@user.city.blank?
      @user.errors[:state]   << "Please enter your state"           unless !@user.state.blank?
      @user.errors[:zip]     << "Please enter your zip/postal code" unless !@user.zip.blank?
      
      if @user.errors.empty?
        redirect_to root_path, notice: "Thank you for filling out the additional information."
        return
      end
    end
    
    render :edit_additional_information
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_modal_terms_of_service.html.haml
%h3 Terms and Conditions for HeritageCookbook.com

= render "terms_of_service"

= link_to "I'm done reading", "#", class: "close-modal button blue"

app/views/accounts/_terms_of_service.html.haml
#terms-of-service
  %p
    NOTICE TO USER - PLEASE READ THE FOLLOWING TERMS AND CONDITIONS CAREFULLY. This Web site (the "Site") is provided by Heritage Cookbook, Inc. ("Heritage") for the use of individuals to share and record recipes with other individuals subject to these terms and conditions of use as amended from time to time (the "Terms and Conditions"). By using this Site, you are deemed to have agreed to the Terms and Conditions. You acknowledge that you have read the Terms and Conditions and agree to be bound by them. IF AT ANY TIME YOU CHOOSE NOT TO ACCEPT THESE TERMS AND CONDITIONS&nbsp;YOU MUST REFRAIN FROM USING&nbsp;THIS SITE.</p>

  %h1 TERMS AND CONDITIONS

  %h2 1. User Conduct

  %p 
    This Site including the ability to contribute material (a "Contribution") on this Site (collectively, the "Services") are provided to you solely for your information and enjoyment. Without limiting the foregoing, you agree not to use the Site or Services to upload, post, copy, reproduce, distribute or otherwise transmit any online information, including but not limited to any Contribution including text, logos or trademarks (the "Content") in any way or to submit any material that infringes any third party's rights or that is unlawful, harmful, defamatory, obscene, libelous, invasive of another's privacy, that contains software viruses, that will harm minors in any way or that will intentionally or unintentionally violate any applicable local, state, national or international law. You further agree not to modify, adapt or exploit any Content.
    %br
    You acknowledge and agree that the Content you view, submit or post is at your own discretion and risk, including any reliance on the accuracy, completeness, or usefulness of such Content and that you may not rely on any such Content. You must abide by all additional copyright notices or other restrictions contained on the Site. If you should violate any of the Terms and Conditions of this Agreement, your right to use this Site will be discontinued immediately without notice to you. Heritage may change the Terms and Conditions, features, specifications and content of the Site from time to time and at any time without actual notice to you. By using the Site after we post any such changes, you agree to accept those changes.

  %h2 2. Unsolicited Materials

  %p In operating the Site, Heritage does not solicit nor does it wish to receive any confidential, secret or proprietary information. Any information or material submitted or sent to Heritage will be deemed not to be confidential or secret. By submitting or sending material to Heritage you represent and warrant that it is original and that no other party has any rights to the material. You are solely responsible for any Contribution or Content that you post on the Site.

  %h2 3. User's Grant of Limited License

  %p 
    By communicating with Heritage, including submitting or sending a Contribution or other information, you grant to Heritage the royalty-free right or license to reproduce and otherwise use such Contribution for the purpose of rendering the Services for which you have subscribed. Heritage may contact you from time to time to request permission to include your Contribution in cookbooks other than that which was created using the Services, or for other commercial, charitable purposes, in which case you agree that such permission will not be unreasonably witheld or delayed. You agree to allow copies of your cookbook to be shown for promotional purposes.

  %h2 4. Linked Sites

  %p 
    You may be able to link to third parties' web sites ("Linked Sites") from the Site. Linked Sites are not, however, reviewed, controlled, or examined by Heritage and Heritage is not responsible for the content or any other materials of such Linked Sites or any additional links contained therein. It is your sole responsibility to comply with the appropriate terms of service and any other obligation of the Linked Site. Permission must be granted by us for any type of link to HeritageCookbook.com. To seek our permission please write to 
    = mail_to CONTACT_EMAIL
    = "."

  %h2 5. Intellectual Property Rights

  %p Heritage owns all rights in and to the Site, all underlying software, HTML and other source code, the site templates, introductory pages, covers and dividers including, but not limited to all copyrights, trademarks, trade secrets, patents and all other intellectual property rights thereto. Except as otherwise specifically provided in these Terms and Conditions, you may not download or save a copy of the Site or any portion thereof for any purpose. You may, however, print a copy of individual screens appearing as part of the Site solely for your personal, non-commercial use or records, provided that any marks, logos or other legends that appear on the copied screens remain on, and are not removed. Heritage reserves all other rights not expressly granted herein. You agree that Heritage shall have the right to use copies of cookbooks generated by the Site for promotional, academic, archival or cultural purposes, provided that Heritage may not sell or otherwise commercially distribute copies of your cookbook without your prior written agreement. For clarity, nothing in these Terms and Conditions grants Heritage ownership of your contributions. Subject to these Terms and Conditions, you are free to reproduce, re-publish or otherwise exploit your own Contribution(s) and the condent part forming hereof. However, Heritage owns all the right, title, and interest, including all copyright, in its unique presentation and formatting of your Contribution and any electronic or physical copies thereof, including, without limitation, the PDF files generated by the Site and all printed cookbooks resulting from the services. All output generated by, or otherwise forming part of, the Site or the Services is the exclusive property of Heritage, and may not be commercailly reproduced, published or otherwise exploited without the prior written consent of Heritage.

  %h2 6. Parental Permission

  %p 
    Heritage may, in its discretion, require users under 18 to obtain the consent of a parent or guardian to view certain content or otherwise. You agree to abide by any such requirements and not to help anyone avoid these restrictions.

  %h2 7. Disclaimer Of Warranties

  %p 
    All Heritage services, including, but not limited to the SITE AND SERVICES ARE PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, CONSTRUCTIVE OR STAUTORY, INCLUDING WITHOUT LIMITATION OF THE FOREGOING, HERITAGE SPECIFICALLY DISCLAIMS ANY AND ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO ANY IMPLIED WARRANTIES OF MERCHANTIBILITY, FITNESS FOR A PARTICULAR PURPOSE OR THE AVAILABILITY, ACCURACY, APPROPRIATENESS, RELIABILITY, TIMELINESS, USEFULNESS, OR OTHERWISE OF THE CONTENT OF THE SITE OR THE SERVICES.
    %br 
    Some jurisdictions do not allow the exclusion of implied warranties, so the above exclusion may not apply to you.

  %h2 8. Limitation Of Liability

  %p 
    You acknowledge that Heritage is not responsible for material submitted to it or posted to the Site. Heritage may, in its sole discretion, refuse or remove any Content in whole or in part that in its judgment is objectionable. You will remain responsible for the accuracy, copyright compliance, legality or any other aspect of a Contribution.

  %p 
    IN NO EVENT WILL HERITAGE, ITS OFFICERS, DIRETORS OR EMPLOYEES BE LIABLE TO ANY PARTY FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES OR ANY OTHER DAMAGES ARISING OUT OF YOUR ACCESS, INABILITY TO ACCESS OR USE OF THE SITE OR FOR ANY INJURY TO YOUR COMPUTER, INCLUSIVE OF VIRUSES, OR FOR ANY OMMISSIONS, INACCURCIES, DELETIONS OR ALTERATIONS ON THE SITE OR OF CONTENT, ANY FAILURE OF PERFORMANCE, DELAY IN OPERATION OR TRANSMISSION OF CONTENT, DEFECT, THEFT, DESTRUCTION OR THAT ANY PORTION OF THE SITE WILL BE FREE OF INFECTION BY VIRUSES OR ANY OTHER DESTRUCTIVE PROPERTIES OR THAT ACCESS TO THE SITE WILL BE UNINTERRUPTED OR ERROR-FREE. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY, THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>

  %h2 9. Indemnification

  %p You agree to defend, indemnify and hold Heritage, its officers, directors and employees harmless from any and all claims, liabilities, costs and expenses, including reasonable attorneys' fees, arising in any way from your use or misuse of the Site or Services, or the uploading, posting, publishing, e-mailing, reproduction, distribution or transmission of any Content or other materials by you or users authorized by you or any violation of the Terms and Conditions. Heritage reserves the right, at its own expense, to assume the exclusive defense and control of any matter subject to indemnification by you, in which event you will cooperate with Heritage in asserting any available defense.

  %h2 10. Applicable Laws / Jurisdiction

  %p You agree that the laws of the Commonwealth of The Bahamas, excluding its conflicts-of-law rules, shall govern the Terms and Conditions. Your use of the Site may be subject to other local, state, national, and international laws. You hereby consent to the exclusive jurisdiction and venue of the courts of the Commonwealth of The Bahamas in all disputes arising out of your use of the Site and any claim involving Heritage or its employees, contractors, officers, directors, telecommunication providers and content providers. Heritage makes no representation that the material available on the Site is appropriate or available for use in other jurisdictions.

  %h2 11. Provisions unenforceable or invalid

  %p 
    If any part of this agreement is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect.

  %h2 12. Assignment

  %p 
    You shall not transfer or assign any of your rights or obligations under this Agreement. Heritage may transfer, assign or sublicense any of its rights and obligations under this agreement to a third party whatsoever.
    %br
    If you have any questions about this policy or our site in general, please contact us at <a href="mailto:admin@heritagecookbook.com">admin@heritagecookbook.com</a></p>

app/views/accounts/edit.html.haml
= errors_for @user if @user.errors.any?

= form_for @user, url: account_path(@user) do |f|
  .control-group
    .align-on-labels
    %p.note<
      If you wish to change your password, please
      = link_to " click here", edit_password_account_path(@user)
  .control-group
    = f.label :first_name, "Your first name:"
    = f.text_field :first_name
  .control-group
    = f.label :last_name, "Your last name:"
    = f.text_field :last_name
  .control-group
    = f.label :email, "Your email address:"
    = f.text_field :email
  .control-group
    = f.label :email_confirmation, "Re-type your email address:"
    = f.text_field :email_confirmation
  .control-group
    = f.label :address, "Address:"
    = f.text_field :address
  .control-group
    .align-on-labels
    = f.text_field :address2
  .control-group
    = f.label :city, "City:"
    = f.text_field :city
  .control-group
    = f.label :state, "State / Province:"
    = f.select :state, [""] + Order::states_reverse
  .control-group
    = f.label :zip, "Zip, Postal Code:"
    = f.text_field :zip
  .control-group
    = f.label :country, "Country:"
    = f.select :country, ["", "Canada", "United States", "Other"]
  .control-group
    = f.label :phone, "Phone Number:"
    = f.text_field :phone
  .control-group
    = f.label :newsletter, "Sign up for our newsletter?"
    = f.check_box :newsletter

  .control-group
    .align-on-labels
    = f.submit "Save Changes", class: "button orange"
    = link_to "Cancel", root_path, class: "button blue"

app/views/accounts/edit_additional_information.html.haml
- content_for :info_panel do
  = render "info_panels/additional_information"

%h3 Additional information
   
= errors_for @user if @user.errors.any?

= form_for @user, url: update_additional_information_account_path(@user) do |f|
  .control-group
    = f.label :address
    = f.text_field :address
  .control-group
    .align-on-labels
    = f.text_field :address2
  .control-group
    = f.label :city
    = f.text_field :city
  .control-group
    = f.label :state, "State / Province"
    = f.select :state, [""] + Order::states_reverse
  .control-group
    = f.label :zip, "Zip, Postal Code"
    = f.text_field :zip
  .control-group
    = f.label :country
    = f.select :country, ["", "Canada", "United States", "Other"]
  .control-group
    = f.label :phone, "Phone Number"
    = f.text_field :phone
  .control-group
    = f.label :newsletter, "Sign up for our newsletter?"
    = f.check_box :newsletter

  .control-group
    .align-on-labels
    = f.submit "Submit Additional Registration Info", class: "orange"
  .control-group
    .align-on-labels
    = link_to "Skip this for now", root_path, class: "button blue"

app/views/accounts/edit_password.html.haml
- content_for :info_panel do
  = render "info_panels/new_password"

%h3 Change your password

= errors_for @user if @user.errors.any?

= form_for @user, url: update_password_account_path(@user) do |f|
  .control-group
    = f.label :old_password, "Your old password:"
    = f.password_field :old_password
  .control-group
    = f.label :password, "A new password:"
    = f.password_field :password
  .control-group
    = f.label :password_confirmation, "Re-type your new password:"
    = f.password_field :password_confirmation
  .control-group
    .align-on-labels
    = f.submit "Change Login Info", class: "orange"
    = link_to "Cancel", root_path, class: "button blue"

app/views/accounts/new.html.haml
- content_for :page_title, "Create your account"
- content_for :headline, "Create your account"

%h3 Signup for a Free Trial

= errors_for @user if @user.errors.any?

= form_for @user, url: accounts_path do |f|
  .control-group
    = f.label :plan, "* Choose a membership plan:"
    = f.select :plan_id, Plan.available_signup_plans
  .control-group
    = f.label :first_name, "* Your first name:"
    = f.text_field :first_name
  .control-group
    = f.label :last_name, "* Your last name:"
    = f.text_field :last_name
  .control-group
    = f.label :email, "* Your email address:"
    = f.text_field :email
  .control-group
    = f.label :email_confirmation, "* Re-type your email address:"
    = f.text_field :email_confirmation
  .control-group
    = f.label :password, "* Your preferred password:"
    = f.password_field :password
  .control-group
    = f.label :password_confirmation, "* Re-type your password:"
    = f.password_field :password_confirmation
  .control-group
    = f.label :how_heard, "Where did you learn about us?"
    = f.select :how_heard, User::HOW_HEARD
  .control-group
    = f.label :cookbook_type, "What type of cookbook would you like to create?"
    = f.select :cookbook_type, User::COOKBOOK_TYPE
  .control-group
    = f.label :address, "Address:"
    = f.text_field :address
  .control-group
    .align-on-labels
    = f.text_field :address2
  .control-group
    = f.label :city, "City:"
    = f.text_field :city
  .control-group
    = f.label :state, "State / Province:"
    = f.select :state, [""] + Order::states_reverse
  .control-group
    = f.label :zip, "Zip, Postal Code:"
    = f.text_field :zip
  .control-group
    = f.label :country, "Country:"
    = f.select :country, ["", "Canada", "United States", "Other"]
  .control-group
    = f.label :phone, "Phone Number:"
    = f.text_field :phone
  .control-group
    = f.label :newsletter_info, "Sign up for our newsletter?"
    = f.check_box :newsletter, checked: true

  .control-group
    = f.label :read_terms_of_services, modal_tag("* Read Terms of Service", render("modal_terms_of_service"))
    %p.note#terms_of_service_review
      I have carefully reviewed the Terms and Conditions above. On registering the HeritageCookbook.com program, I hereby agree  to the terms and conditions as set out under the Disclaimer

  .control-group
    = f.label :terms_of_service, "I Agree"
    = f.check_box :terms_of_service

  .control-group
    .align-on-labels
    = f.submit "Submit Registration Info", class: "orange"

  .control-group
    .align-on-labels
    %p.note Fields marked with an * must be entered

app/views/accounts/recover_password.html.haml
- content_for :page_title, "Forgot your password?"
- content_for :headline, "Forgot your password?"

%h3 Request a new password

= errors_for @user if @user.errors.any?

= form_for @user, url: new_password_path do |f|
  .control-group
    = f.label :email, "Email Address"
    = f.text_field :email
  .control-group
    .align-on-labels
    = f.submit "Request a new password", class: "orange"
  .control-group
    .align-on-labels
    = link_to "Cancel", root_path, class: "button blue"

app/views/accounts/upgrade.html.haml
%h3= (@selected_plan) ? "Confirm your membership plan:" : "Choose your membership plan:"
= form_tag process_payment_account_path(current_user) do
  #plans
    - @plans_available.each do |plan|
      .on-line-control
        = radio_button_tag :plan, plan[1], (@plan.id == plan[1])
        = label_tag plan[1], plan[0]
  = submit_tag "Go to the payment website", class: "orange"
  = link_to "Cancel", root_path, class: "button blue"

/ # Display a notice box with testing Paypal credentials
- if Rails.env.development?
  .staging
    %h5 Testing Paypal credentials
    %ul.note
      %li 
        %strong email: 
        testing@heritagecookbook.com 
      %li 
        %strong password: 
        heritage